#!/bin/sh

# Copyright (c) 2020 Antti Kivi
# Licensed under the MIT License

set -e

readonly VERSION="$(cat ${0%/*}/version.txt)"
readonly NAME="Effective Elegy"

echo "Running the Bourne shell build script of $NAME"
echo "Building $NAME version $VERSION"
echo "The type of the current OS is $OSTYPE"

readonly SOURCE_DIRECTORY_NAME="src"
readonly DISTRIBUTION_DIRECTORY_NAME="dist"

readonly ROOT_DIRECTORY="."

readonly SOURCE_DIRECTORY="$ROOT_DIRECTORY/$SOURCE_DIRECTORY_NAME"
readonly DISTRIBUTION_DIRECTORY="$ROOT_DIRECTORY/$DISTRIBUTION_DIRECTORY_NAME"

readonly TEMPORARY_FILE_NAME="tmp.txt"
readonly PRODUCT_FILE_NAME="effective-elegy-$VERSION.txt"

readonly TEMPORARY_FILE="$DISTRIBUTION_DIRECTORY/$TEMPORARY_FILE_NAME"
readonly PRODUCT_FILE="$DISTRIBUTION_DIRECTORY/$PRODUCT_FILE_NAME"

readonly BACKUP_EXTENSION=".tmp"

# Set the source files.

SOURCE_FILES=""
SOURCE_FILES="$SOURCE_FILES $SOURCE_DIRECTORY/preamble.txt"
SOURCE_FILES="$SOURCE_FILES $SOURCE_DIRECTORY/body.txt"
SOURCE_FILES="$SOURCE_FILES $SOURCE_DIRECTORY/future.txt"
SOURCE_FILES="$SOURCE_FILES $SOURCE_DIRECTORY/warranty.txt"

# Check the build directory and destination file.

if [ ! -d "$DISTRIBUTION_DIRECTORY" ]; then
  echo "No distribution directory found"
  echo "Thus, creating directory '$DISTRIBUTION_DIRECTORY'"
  mkdir $DISTRIBUTION_DIRECTORY
  echo "Created directory '$DISTRIBUTION_DIRECTORY'"
fi

if [ -e "$PRODUCT_FILE" ]; then
  echo "File '$PRODUCT_FILE' already exists"
  echo "Thus, it'll be deleted before the build is performed"
  rm $PRODUCT_FILE
  echo "Deleted file '$PRODUCT_FILE'"
fi

if [ -e "$TEMPORARY_FILE" ]; then
  echo "File '$TEMPORARY_FILE' already exists"
  echo "Thus, it'll be deleted before the build is performed"
  rm $TEMPORARY_FILE
  echo "Deleted file '$TEMPORARY_FILE'"
fi

# Build the licence.

echo "Building the licence to file '$PRODUCT_FILE'"

for file in $SOURCE_FILES; do
  echo "Concatenating file '$file'"
  (cat "$file"; echo) >> $TEMPORARY_FILE
done

case "$OSTYPE" in
  "darwin"*)
    sed -i "$BACKUP_EXTENSION" -e "s/{VERSION}/$VERSION/g" $TEMPORARY_FILE
    rm "$TEMPORARY_FILE$BACKUP_EXTENSION"
    sed -i "" -e "$ d" $TEMPORARY_FILE ;;

  *)
    sed -i "s/{VERSION}/$VERSION/g" $TEMPORARY_FILE
    sed -i "$ d" $TEMPORARY_FILE ;;
esac

fold -w 80 -s $TEMPORARY_FILE > $PRODUCT_FILE

rm $TEMPORARY_FILE

echo "Built the licence to file '$PRODUCT_FILE'"

# Print the final licence.

echo "The licence is currently the following:\n"

cat $PRODUCT_FILE

# Print one empty line to make the shell output look better.

echo ""
